version: '3.2'
services:
    balderdash:
        image: at88mph/balderdash:alpine
        ports:
            - '4000:4000'
        network_mode: host
        depends_on:
            - 'postgresql'
        volumes:
            - './:/usr/src/app'

    postgresql:
        image: postgres:alpine
        ports:
            - '5432:5432'
        network_mode: host
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: balderdash_dev
            PGDATA: /var/lib/postgresql/data/balderdashdata
        volumes:
            - 'balderdashdata:/var/lib/postgresql/data/balderdashdata'

volumes:
    balderdashdata:
