version: '3.2'
services:
    postgresql:
        image: postgres:alpine
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: balderdash_dev
            PGDATA: /var/lib/postgresql/data/balderdashdata
        volumes:
            - 'balderdashdata:/var/lib/postgresql/data/balderdashdata'

volumes:
    balderdashdata: